import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Provider } from '@/components/ui/provider'
import { MainLayout } from './components/main-layout'

const montserratSans = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang='pt-br'>
      <body className={`${montserratSans.variable}`}>
        <Provider>
          <MainLayout>{children}</MainLayout>
        </Provider>
      </body>
    </html>
  )
}
